title: Hello, world! I'm Amit Kumar Pradhan 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: '/dsprojects/' # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Amit Kumar Pradhan # add your name
author-img: amitkp.jpg # add your photo
about-author: I am a budding professional in Data Science focusing on Data Analysis, Visualization and Predictive Modeling. I am a self-taught. # add description
twitter: akpradhn # add your Twitter handle
facebook: akpradhn # add your Facebook handle
github: akpradhn # add your Github handle
linkedin: akpradhn # add your Linkedin handle
email: akpradhn@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
